"use client";
import Link from "next/link";
import { useState, useTransition } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { LoaderCircle } from "lucide-react";
import { signIn, signUp } from "@/features/auth/actions/auth-actions";
import { authSchema, type AuthCredentials } from "@/features/auth/schemas/auth-schema";
import { Button } from "@/components/ui/button";
export function AuthForm({ mode }: { mode: "login" | "register" }) { const login = mode === "login"; const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<{ type: "error" | "success"; text: string } | null>(null); const { register, handleSubmit, formState: { errors } } = useForm<AuthCredentials>({ resolver: zodResolver(authSchema) }); const submit = (values: AuthCredentials) => { setMessage(null); startTransition(async () => { const result = await (login ? signIn(values) : signUp(values)); if (result) setMessage(result.error ? { type: "error", text: result.error } : { type: "success", text: result.success ?? "" }); }); }; return <form onSubmit={handleSubmit(submit)} className="space-y-5" noValidate><label className="block space-y-2 text-sm font-medium text-slate-200">Email address<input {...register("email")} type="email" autoComplete="email" placeholder="you@example.com" className="h-11 w-full rounded-xl border border-white/10 bg-slate-950/60 px-3 text-base text-white outline-none transition placeholder:text-slate-600 focus:border-cyan-300/60 focus:ring-2 focus:ring-cyan-300/20" />{errors.email && <span className="block text-xs font-normal text-rose-300">{errors.email.message}</span>}</label><label className="block space-y-2 text-sm font-medium text-slate-200">Password<input {...register("password")} type="password" autoComplete={login ? "current-password" : "new-password"} placeholder="At least 8 characters" className="h-11 w-full rounded-xl border border-white/10 bg-slate-950/60 px-3 text-base text-white outline-none transition placeholder:text-slate-600 focus:border-cyan-300/60 focus:ring-2 focus:ring-cyan-300/20" />{errors.password && <span className="block text-xs font-normal text-rose-300">{errors.password.message}</span>}</label>{message && <p role="status" className={message.type === "error" ? "text-sm text-rose-300" : "text-sm text-emerald-200"}>{message.text}</p>}<Button type="submit" className="w-full" disabled={pending}>{pending && <LoaderCircle className="size-4 animate-spin" aria-hidden="true" />}{login ? "Sign in" : "Create account"}</Button><p className="text-center text-sm text-slate-400">{login ? "New to AI Study Buddy?" : "Already have an account?"}{" "}<Link href={login ? "/register" : "/login"} className="font-medium text-cyan-200 hover:text-cyan-100">{login ? "Create an account" : "Sign in"}</Link></p></form>; }
